### ISSUE TITLE
mexIPOPT interface for new version of IPOPT

### ISSUE THREAD

**Issue by bluearrow98** [ebertolazzi/mexIPOPT#11]
Hello!

I have installed the latest version of IPOPT (3.14) using coinbrew on my PC. I would like to use this version of IPOPT with mexIPOPT  on my MATLAB. But it seems like that the recent release of mexIPOPT comes already with an IPOPT (v3.13.3). How can I compile mexIPOPT to use the newer version of IPOPT? Further, in future if I install a new linear solver for IPOPT then how to make sure mexIPOPT uses that new solver. Any leads are appreciated!

Best,
Rahul

**Comment by ebertolazzi** [comment]
Unfortunately compile and link IPOPT on WINDOWS is difficult.
However if you have installed a working version of IPOPT you can try to compile the MEX using CompileIpoptMexLib.m modifying IPOPT_HOME. Good luck.

**Comment by bluearrow98** [comment]
Thanks for the hint. I had to also replace the dll.a files with that of the new IPOPT version. But ultimately, it worked :)
