### ISSUE TITLE
suggestion to move binaries to separate repo

### ISSUE THREAD

**Issue by rdzman** [ebertolazzi/mexIPOPT#17]
First, thanks @ebertolazzi, for your work on keeping the IPOPT MEX interface alive.

I had a quick suggestion. In my opinion, it would be ideal to split this into at least two separate repositories.

The first, and main one would consist of a minimal repository with only the source and files for the MEX interface itself, with no binaries, and independent of any particular IPOPT version, OS platform or version, MATLAB/Octave version, etc. Essentially this would include everything you need to build the MEX for a system that already has IPOPT and MATLAB/Octave installed. This would hopefully change very rarely.

Anything specific to a particular build, i.e. lPOPT sources and/or libraries, MEX binaries, etc, on the other hand, could be kept in a separate repository (or repositories). You could either dump all of this in a single repository, or it might make sense to have a separate build-specific repository for each build with a README with details of the build environment (OS, IPOPT, MATLAB/Octave versions) and the MEX file and any libraries it depends on.

What do you think?

**Comment by ebertolazzi** [comment]
> First, thanks @ebertolazzi, for your work on keeping the IPOPT MEX interface alive.
> 
> I had a quick suggestion. In my opinion, it would be ideal to split this into at least two separate repositories.
> 
> The first, and main one would consist of a minimal repository with only the source and files for the MEX interface itself, with no binaries, and independent of any particular IPOPT version, OS platform or version, MATLAB/Octave version, etc. Essentially this would include everything you need to build the MEX for a system that already has IPOPT and MATLAB/Octave installed. This would hopefully change very rarely.
> 
> Anything specific to a particular build, i.e. lPOPT sources and/or libraries, MEX binaries, etc, on the other hand, could be kept in a separate repository (or repositories). You could either dump all of this in a single repository, or it might make sense to have a separate build-specific repository for each build with a README with details of the build environment (OS, IPOPT, MATLAB/Octave versions) and the MEX file and any libraries it depends on.
> 
> What do you think?

Is a very good idea, 
I will reorganize the code as suggested in the next releases.

> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.

regards,

Enrico Bertolazzi
__________________________________________________________________________
Dipartimento di Ingegneria Industriale            
Università degli Studi di Trento
https://e.bertolazzi.dii.unitn.it

**Comment by rdzman** [comment]
Seeing you've closed this issue, I was just curious about your plans relative to my proposal above. It seems this repo still includes platform-specific binaries in `toolbox/bin` and IPOPT source in `toolbox/src_ipopt_osx/coin-or`.

And where can we find the binaries that have been removed? Are they in another repo?

**Comment by ebertolazzi** [comment]
Sorry, I plan to move binary in a submodules and reorganize compilation with cmake but I am very busy so that I do it in my spare time.

**Comment by rdzman** [comment]
👍 Sounds good, just curious. And thanks again for your work to keep a MATLAB and Octave interface to IPOPT alive, in your spare time, no less. It's appreciated.
