### ISSUE TITLE
Using intermediate callback crashes matlab

### ISSUE THREAD

**Issue by worc4021** [ebertolazzi/mexIPOPT#2]
Hi!

I love your new interface to Ipopt! However, I seem to have an issue when I run examplehs038.m. It crashes matlab, when I turn off the intermediate callback, it works just fine. Is this a known issue or did I do something wrong? All other examples work just fine. I noticed that the examples are copies of the ones distributed with the older ipopt mex code, and when I build that one and try examplehs038 it works fine.

Cheers,
Manuel

**Comment by ebertolazzi** [comment]
> 
> Hi!
> 
> I love your new interface to Ipopt! However, I seem to have an issue when I run examplehs038.m. It crashes matlab, when I turn off the intermediate callback, it works just fine. Is this a known issue or did I do something wrong? All other examples work just fine. I noticed that the examples are copies of the ones distributed with the older ipopt mex code, and when I build that one and try examplehs038 it works fine.
> 
> Cheers,
> Manuel

Dear Manuel,

thank you for the reporting of the bug.
I have removed the bug and updated to ipopt 3.12.12,
moreover I added a precompiled mex file for windows
and octave on linbux.

best regards,

Enrico Bertolazzi
__________________________________________________________________________
Dipartimento di Ingegneria Industriale             
Università degli Studi di Trento
http://www.ing.unitn.it/~bertolaz
