### ISSUE TITLE
Couldn't use finite-difference gradient and jacobian approximation

### ISSUE THREAD

**Issue by myozinaung** [ebertolazzi/mexIPOPT#20]
I found the options to use finite-difference gradient and jacobian in the following link.
https://coin-or.github.io/Ipopt/OPTIONS.html

I try to use those options like this:

  options.nlp.jacobian_approximation = 'finite-difference-values';
  options.nlp.gradient_approximation = 'finite-difference-values';

or

  options.ipopt.jacobian_approximation = 'finite-difference-values';
  options.ipopt.gradient_approximation = 'finite-difference-values';

But they don't seem to work.

**Comment by ebertolazzi** [comment]
probably depend on IPOPT library.
