### ISSUE TITLE
precompiled lib?

### ISSUE THREAD

**Issue by wly2014** [ebertolazzi/mexIPOPT#3]
I want to use the dll and hpp in the folder "binary" on Windows (in C language). When I run the code, Visual Studio told me 'error LNK2019: unresolved external symbol "IpoptSolve"'. I think that I may lose the lib file of ipopt? Can you support the lib file? thanks

**Comment by ebertolazzi** [comment]
you cannot use Visual Studio, the binary are done for MINGW
