### ISSUE TITLE
error in compile_win.m

### ISSUE THREAD

**Issue by P705** [ebertolazzi/mexIPOPT#5]
I wanna create ipopt.mex by compile_win.m but below error was appeared. how can
 handle this?
![1](https://user-images.githubusercontent.com/57658660/87942122-5dcd9e00-cab1-11ea-85a8-1ad5d4ead2a7.JPG)

**Comment by ebertolazzi** [comment]
The binary files are compiled for MINGW. To compile MEX you cannot use Visual Studio but MINGW. Install MINGW support for MATLAB: see https://it.mathworks.com/matlabcentral/fileexchange/52848-matlab-support-for-mingw-w64-c-c-compiler

**Comment by P705** [comment]
Hi againI deploy my code to .net dll, but the ipopt mex file doesn't run and dll crash without any error. what's the problem and how can I handle this?
    On Tuesday, July 21, 2020, 01:35:43 AM GMT+4:30, Enrico Bertolazzi <notifications@github.com> wrote:  
 
 


The binary files are compiled for MINGW. To compile MEX you cannot use Visual Studio but MINGW. Install MINGW support for MATLAB: see https://it.mathworks.com/matlabcentral/fileexchange/52848-matlab-support-for-mingw-w64-c-c-compiler
