### ISSUE TITLE
Error in compile_linux.m

### ISSUE THREAD

**Issue by P705** [ebertolazzi/mexIPOPT#6]
How can handle below error ?
![Screenshot from 2020-07-27 15-18-31](https://user-images.githubusercontent.com/57658660/88534220-d508b200-d01c-11ea-9954-c77ef0017b83.png)

**Comment by ebertolazzi** [comment]
Have installed IPOPT? PREFIX must be the path where IPOPT is installed e.g. /usr or /usr/local.

**Comment by P705** [comment]
How can install IPOPT?
I try to compile ipopt based on README_linux_how_to_compile_ipopt.md, but the BLAS package not found error appears as below images.
![Screenshot from 2020-07-28 14-44-09](https://user-images.githubusercontent.com/57658660/88653346-2f6b4680-d0e1-11ea-9a9e-e1781815d6d7.png)
![Screenshot from 2020-07-28 14-44-58](https://user-images.githubusercontent.com/57658660/88653395-3eea8f80-d0e1-11ea-8f87-cb6ad0eb45b4.png)

**Comment by ebertolazzi** [comment]
in linux UBUNTU you can install IPOPT using 

sudo apt install coinor-libipopt-dev

on MAC (OSX)

install homebrew and

brew install ipopt
