### ISSUE TITLE
Add other solvers like MA57

### ISSUE THREAD

**Issue by ShuaiHeng21** [ebertolazzi/mexIPOPT#8]
I am thankful for your work. Now I want to use  MA57 from the HSL Mathematical Software Library
(see http://www.hsl.rl.ac.uk). Do you know how to build IPOPT using MA57 this solver? Is it just need to add the file in ThirdParty and chang the path directing to MA57?  I just applied for the download for MA57. Hope you can give me some suggestions.

**Comment by ebertolazzi** [comment]
sorry, cant help you. Now IPOPT come with coinbrew installer and I do not know how to add MA57. However HSL now added some support for IPOPT (http://www.hsl.rl.ac.uk/ipopt/) try to read its documentation.
